# Análisis de unidades luminosas (farolas)

Primero, instalaré las librerías de pandas.

In [ ]:
!pip install pandas

A continuación, importo las librerías.

In [2]:
import pandas as pd

In [3]:
url_movilidad = "https://datos.madrid.es/egob/catalogo/300573-1-unidades-luminosas-farolas.csv"

In [4]:
url_movilidad

'https://datos.madrid.es/egob/catalogo/300573-1-unidades-luminosas-farolas.csv'

In [5]:
df = pd.read_csv(url_movilidad)

HTTPError: HTTP Error 403: Forbidden

In [6]:
df = pd.read_csv('./20220408_DATOS_ABIERTOS_UNIDAD_LUMINOSA_.csv')

In [7]:
df

,tipo_bloqu,C,50;TIPOL,C.1,254;VIA_CLASE,C.2,254;VIA_PAR,C.3,254;VIA_NOMBRE,C.4,...,0;BARRIO,N.3,10.3,0;X_UTM,N.4,19,11;Y_UTM,N.5,19.1,11
0,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;3;200...,48120000000;4480670,67020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;10;31...,64160000000;4480740,99560000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GLED001;LED;PLAZA;DE;MAR DEL PLATA;NUMERO;12;1...,07500000000;4480679,16380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;21;...,53530000000;4480644,66020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;19;...,16270000000;4480635,1820000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233304,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;4;310...,72200000000;4480688,4830000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233305,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;6;310...,87790000000;4480710,60620000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233306,LBE026;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;111...,35970000000;4480727,38290000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233307,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;111...,63950000000;4480730,2000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233308,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;1;111...,21550000000;4480658,20960000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233309 entries, 0 to 233308
Data columns (total 31 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   tipo_bloqu      233309 non-null  object
 1   C               233309 non-null  object
 2   50;TIPOL        233309 non-null  int64
 3   C.1             0 non-null       float64
 4   254;VIA_CLASE   0 non-null       float64
 5   C.2             0 non-null       float64
 6   254;VIA_PAR     0 non-null       float64
 7   C.3             0 non-null       float64
 8   254;VIA_NOMBRE  0 non-null       float64
 9   C.4             0 non-null       float64
 10  254;CLASE_APP   0 non-null       float64
 11  C.5             0 non-null       float64
 12  254;NUMERO      0 non-null       float64
 13  N               0 non-null       float64
 14  10              0 non-null       float64
 15  0;COD_NDP       0 non-null       float64
 16  N.1             0 non-null       float64
 17  10.1            0 non-null       float64
 18  0;DISTRITO      0 non-null       float64
 19  N.2             0 non-null       float64
 20  10.2            0 non-null       float64
 21  0;BARRIO        0 non-null       float64
 22  N.3             0 non-null       float64
 23  10.3            0 non-null       float64
 24  0;X_UTM         0 non-null       float64
 25  N.4             0 non-null       float64
 26  19              0 non-null       float64
 27  11;Y_UTM        0 non-null       float64
 28  N.5             0 non-null       float64
 29  19.1            0 non-null       float64
 30  11              0 non-null       float64
dtypes: float64(28), int64(1), object(2)
memory usage: 55.2+ MB

In [9]:
df.head()

,tipo_bloqu,C,50;TIPOL,C.1,254;VIA_CLASE,C.2,254;VIA_PAR,C.3,254;VIA_NOMBRE,C.4,...,0;BARRIO,N.3,10.3,0;X_UTM,N.4,19,11;Y_UTM,N.5,19.1,11
0,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;3;200...,48120000000;4480670,67020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;10;31...,64160000000;4480740,99560000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GLED001;LED;PLAZA;DE;MAR DEL PLATA;NUMERO;12;1...,07500000000;4480679,16380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;21;...,53530000000;4480644,66020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;19;...,16270000000;4480635,1820000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Hasta ahora, hemos importado la libreria de datos en el phyton, y hemos enseñado las primeras variables (antes veíamos muchas y ahora solo las primeras 5)

In [11]:
df.columns

Index(['tipo_bloqu', 'C', '50;TIPOL', 'C.1', '254;VIA_CLASE', 'C.2',
       '254;VIA_PAR', 'C.3', '254;VIA_NOMBRE', 'C.4', '254;CLASE_APP', 'C.5',
       '254;NUMERO', 'N', '10', '0;COD_NDP', 'N.1', '10.1', '0;DISTRITO',
       'N.2', '10.2', '0;BARRIO', 'N.3', '10.3', '0;X_UTM', 'N.4', '19',
       '11;Y_UTM', 'N.5', '19.1', '11'],
      dtype='object')

Estos de arriba son los nombres de las columnas extraidos de la tabla.

In [12]:
df.tail()

,tipo_bloqu,C,50;TIPOL,C.1,254;VIA_CLASE,C.2,254;VIA_PAR,C.3,254;VIA_NOMBRE,C.4,...,0;BARRIO,N.3,10.3,0;X_UTM,N.4,19,11;Y_UTM,N.5,19.1,11
233304,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;4;310...,72200000000;4480688,4830000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233305,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;6;310...,87790000000;4480710,60620000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233306,LBE026;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;111...,35970000000;4480727,38290000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233307,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;111...,63950000000;4480730,2000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233308,LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;1;111...,21550000000;4480658,20960000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Esta vez hemos seleccionado las últimas 5 filas de la tabla.

In [15]:
df.set_index('tipo_bloqu')

,C,50;TIPOL,C.1,254;VIA_CLASE,C.2,254;VIA_PAR,C.3,254;VIA_NOMBRE,C.4,254;CLASE_APP,...,0;BARRIO,N.3,10.3,0;X_UTM,N.4,19,11;Y_UTM,N.5,19.1,11
tipo_bloqu,,,,,,,,,,,,,,,,,,,,,
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;3;20040016;16;4;445648,48120000000;4480670,67020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;10;31024246;16;4;445610,64160000000;4480740,99560000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GLED001;LED;PLAZA;DE;MAR DEL PLATA;NUMERO;12;11119324;16;4;445680,07500000000;4480679,16380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;21;11119327;16;4;445669,53530000000;4480644,66020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;19;11119326;16;4;445651,16270000000;4480635,1820000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;4;31022348;16;4;445636,72200000000;4480688,4830000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;6;31022349;16;4;445626,87790000000;4480710,60620000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LBE026;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;11119314;16;4;445612,35970000000;4480727,38290000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;11119314;16;4;445616,63950000000;4480730,2000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;1;11119309;16;4;445640,21550000000;4480658,20960000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.set_index('tipo_bloqu')['C']

tipo_bloqu
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;3;20040016;16;4;445648       48120000000;4480670
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;10;31024246;16;4;445610      64160000000;4480740
GLED001;LED;PLAZA;DE;MAR DEL PLATA;NUMERO;12;11119324;16;4;445680     07500000000;4480679
FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;21;11119327;16;4;445669    53530000000;4480644
FFLED005;LED;CALLE;DEL;MAR AMARILLO;NUMERO;19;11119326;16;4;445651    16270000000;4480635
                                                                             ...
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;4;31022348;16;4;445636       72200000000;4480688
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;6;31022349;16;4;445626       87790000000;4480710
LBE026;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;11119314;16;4;445612       35970000000;4480727
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;9;11119314;16;4;445616       63950000000;4480730
LBE002;DESCARGA;CALLE;DE LAS;ERAS;NUMERO;1;11119309;16;4;445640       21550000000;4480658
Name: C, Length: 233309, dtype: object

In [22]:
df.set_index('tipo_bloqu')['C'].plot(title="unidades luminosas")

TypeError: no numeric data to plot